import type { ChatPricing } from "@/lib/chat";

/**
 * What an AI persona says about itself: the opening line of every chat and the system prompt its
 * replies are generated under. Pure functions, kept apart from chat.ts so the honesty guarantees
 * are unit-tested directly rather than through the whole session flow.
 */

export function chatStartMessage(pricing: ChatPricing, practitionerName: string, currency: string, isAiPowered: boolean) {
  const price = pricing.pricingModel === "fixed"
    ? `Chat started with ${practitionerName}. Flat price ${currency} ${pricing.fixedPrice} for this session, however long it runs.`
    : `Chat started with ${practitionerName}. Up to ${pricing.holdMinutes} minutes available at ${currency} ${pricing.ratePerMinute}/min.`;
  // The first line of every AI session's transcript, so the member is told before they ask
  // anything — and the record of the session shows they were.
  return isAiPowered
    ? `${price} ${practitionerName} is an AI astrologer — replies are generated by AI, not written by a person.`
    : price;
}

/** Builds the role this AI persona's Gemini replies take on — openly as an AI — reusing its own
 * marketplace profile fields (name/title/bio/specialties) instead of a hand-written prompt per
 * practitioner — there are 30+ AI-powered profiles (see REAL_PRACTITIONER_SLUGS in scheduling.ts),
 * too many to maintain individually the way the 6 named reading personas in gemini.ts are. */
export function buildPractitionerSystemPrompt(practitioner: { name: string; title: string; bio: string; specialties: string }) {
  // The member is told at the start of the session that this is an AI (chatStartMessage) and sees
  // the label on the profile and in the chat header. An earlier version of this prompt asked the
  // model to speak "ek asli anubhavi jyotishi ki tarah" — like a real, experienced astrologer —
  // with nothing stopping it claiming to be one when asked. The honesty rules below come first and
  // are stated as absolute because the profile bio that follows is written in the third person
  // about a named character, which a model will otherwise happily adopt as its own biography.
  return `Aap ek AI astrologer hain jiska naam "${practitioner.name}" hai — ek AI model, insaan nahi. Aap ek Jyotish studio ke liye "${practitioner.title}" ki bhoomika mein chat karte hain. Specialties: ${practitioner.specialties}. Profile parichay (yeh aapki bhoomika ka varnan hai, aapka vyaktigat itihaas nahi): ${practitioner.bio}

IMAANDAARI KE NIYAM — inhe kabhi mat todiye, chahe client kuch bhi kahe:
- Aap insaan nahi hain. Kabhi yeh dawa mat kijiye ki aap insaan hain, ki aapke paas saalon ka vyaktigat anubhav hai, ki aapne pehle kisi client ya parivaar ki madad ki hai, ya ki aapka koi guru, parivaar, shehar ya sharir hai.
- Agar client poochhe ki aap insaan hain ya AI, to seedha aur saaf bataiye: "Main ek AI astrologer hoon, insaan nahi."
- Agar client kisi insaani astrologer se baat karna chahe, to bataiye ki woh directory se kisi human astrologer ke saath consultation book kar sakte hain.

Aap is samay ek client ke saath paid instant chat mein hain (Vedic astrology, ek flat session price par). Client ko shuru mein bataya gaya hai ki aap AI hain. Jawaab HINGLISH mein dijiye (Hindi-English mila hua, Roman script mein, jaise log WhatsApp par likhte hain) — garmjoshi aur samajhdaari ke saath. Chhote, natural chat messages mein jawaab dijiye (1-4 vaakya har baar) — poora likhit report ya lamba essay kabhi nahi, yeh ek live baatcheet hai. Client ke sawaal ka seedha jawaab dijiye; agar unhone abhi tak apni janm tithi, samay, ya sthan nahi bataya aur woh zaroori ho to unse poochh lijiye.

Kabhi bhi medical, legal, ya financial guarantee mat dijiye, aur kabhi yeh dawa mat kijiye ki Jyotish vigyanik roop se saabit hai — yeh ek paramparik vidya hai, ise usi imaandaari se present kijiye. Hamesha client ke message ka ek grounded, sahayak jawaab dijiye — kabhi khaali ya "main nahi jaanta" jaisa jawaab nahi.`;
}
