import { describe, expect, it } from "vitest";

import { buildPractitionerSystemPrompt, chatStartMessage } from "@/lib/ai-persona-prompt";

const persona = { name: "Anika Sharma", title: "Career astrologer", bio: "Anika has helped thousands of clients.", specialties: "Career" };
const fixed = { pricingModel: "fixed", ratePerMinute: 0, fixedPrice: 149, holdAmount: 149, holdMinutes: 60 } as const;
const metered = { pricingModel: "metered", ratePerMinute: 20, fixedPrice: null, holdAmount: 200, holdMinutes: 10 } as const;

describe("AI persona system prompt", () => {
  const prompt = buildPractitionerSystemPrompt(persona);

  it("tells the model it is an AI and not a person", () => {
    expect(prompt).toContain("ek AI model, insaan nahi");
  });

  it("forbids claiming to be human or to have personal history", () => {
    expect(prompt).toContain("Aap insaan nahi hain");
    expect(prompt).toContain("saalon ka vyaktigat anubhav");
  });

  it("requires a straight answer when asked whether it is human", () => {
    expect(prompt).toContain("Main ek AI astrologer hoon, insaan nahi.");
  });

  it("no longer asks the model to speak like a real, experienced astrologer", () => {
    expect(prompt).not.toMatch(/asli anubhavi jyotishi/i);
  });

  it("frames the bio as a role description, not the model's own history", () => {
    expect(prompt).toContain("aapki bhoomika ka varnan hai, aapka vyaktigat itihaas nahi");
    // The honesty rules must come before the bio, or the model reads the bio first.
    expect(prompt.indexOf("IMAANDAARI KE NIYAM")).toBeGreaterThan(-1);
  });

  it("keeps the persona's name and specialties so replies stay on topic", () => {
    expect(prompt).toContain("Anika Sharma");
    expect(prompt).toContain("Career");
  });
});

describe("chat opening message", () => {
  it("discloses an AI persona in the first line of the session", () => {
    expect(chatStartMessage(fixed, "Anika Sharma", "INR", true))
      .toBe("Chat started with Anika Sharma. Flat price INR 149 for this session, however long it runs. Anika Sharma is an AI astrologer — replies are generated by AI, not written by a person.");
  });

  it("says nothing about AI for a human astrologer", () => {
    expect(chatStartMessage(metered, "Arun Dubey", "INR", false))
      .toBe("Chat started with Arun Dubey. Up to 10 minutes available at INR 20/min.");
  });
});
