export type FaqEntry = { id: string; category: string; question: string; answer: string };

export const MEMBER_FAQ: FaqEntry[] = [
  { id: "m-book-1", category: "Bookings", question: "How do I book a session with an astrologer?", answer: "Go to Astrologers or Book, pick a practitioner and a reading type, choose an open time slot, and confirm your birth details. You'll get a confirmation with the exact date and time." },
  { id: "m-book-2", category: "Bookings", question: "Can I reschedule or cancel a booking?", answer: "Yes — open My Consultations, find the session, and use Reschedule or Cancel. Cancellations made within the studio's cancellation window may not be eligible for a refund; check the exact cutoff shown on your booking." },
  { id: "m-book-3", category: "Bookings", question: "What happens after I book a session?", answer: "The practitioner reviews your birth details before the session. You'll get a reminder as the time approaches, and the session details are always visible under My Consultations." },
  { id: "m-pay-1", category: "Payments", question: "What payment methods are accepted?", answer: "Card, UPI, netbanking, and wallets via Razorpay, wherever online payments are enabled. All receipts are available under Billing & Receipts." },
  { id: "m-pay-2", category: "Payments", question: "How do refunds work?", answer: "Eligible cancellations are refunded to your original payment method automatically. Refund timing depends on your bank/UPI provider, typically a few business days." },
  { id: "m-plan-1", category: "Membership", question: "What do membership plans include?", answer: "Paid plans include a discount on session prices, applied automatically at checkout — no code needed. Compare plans on the Pricing page." },
  { id: "m-plan-2", category: "Membership", question: "How do I upgrade or cancel my plan?", answer: "Manage your subscription from your dashboard's subscription section — upgrades apply immediately, and cancellation takes effect at the end of your current billing period." },
  { id: "m-wallet-1", category: "Live Chat", question: "How does the wallet-based live chat work?", answer: "Recharge your wallet, then start an instant chat with an available astrologer. The session meters by the minute and deducts from your wallet balance in real time — you'll see the balance as you chat." },
  { id: "m-wallet-2", category: "Live Chat", question: "What if my wallet runs out mid-chat?", answer: "You'll get a low-balance warning before the session ends. Top up any time from the Wallet page to keep the conversation going." },
  { id: "m-ai-1", category: "AI Reading", question: "Is the AI reading really free?", answer: "Your very first AI reading on /ask is free. Every reading after that is a flat ₹149, paid before the answer is generated." },
  { id: "m-ai-2", category: "AI Reading", question: "Who answers my question — a person or AI?", answer: "The /ask tool is answered by our AI Jyotish guide, Shree Santram Shashtri, based on the birth details and question you provide. For a human practitioner, book a live consultation instead." },
  { id: "m-kundli-1", category: "Kundli Tools", question: "Is the Kundli report a real chart, or AI-generated text?", answer: "It's a real chart — computed from actual planetary positions (Lagna, all 9 grahas, their rashi and nakshatra) using an astronomical engine, not AI. Only the free-form question tool uses AI." },
  { id: "m-kundli-2", category: "Kundli Tools", question: "What does Kundli Matching actually calculate?", answer: "The classical Ashtakoot Guna Milan — all 8 kootas (Varna, Vashya, Tara, Yoni, Graha Maitri, Gana, Bhakoot, Nadi) scored out of 36, from both people's real Moon positions. It needs exact birth date, time, and place for both people to be accurate." },
  { id: "m-kundli-3", category: "Kundli Tools", question: "Why does the tool ask for an exact birth place?", answer: "Real planetary positions depend on your exact birth location and time, not just your date of birth. If your city isn't recognized, try a nearby major city or add your state/country." },
  { id: "m-panchang", category: "Kundli Tools", question: "Is the daily Panchang live?", answer: "Yes — tithi, nakshatra, yoga, karana, sunrise/sunset, and muhurat windows are computed fresh from real astronomical data for New Delhi every time you load the page." },
  { id: "m-horoscope", category: "Kundli Tools", question: "How is my daily horoscope generated?", answer: "It's based on where the Moon is actually transiting today relative to your sign — a real, changing astronomical position, not a random daily message." },
  { id: "m-gem-1", category: "Gemstones", question: "How do I track my gemstone order?", answer: "Open Gemstone Orders in your dashboard for live status, or use the order confirmation link sent to your email." },
  { id: "m-gem-2", category: "Gemstones", question: "Can I return a gemstone?", answer: "Check the return policy on the product page — most items have a return window from delivery, provided the certification and packaging are intact." },
  { id: "m-account-1", category: "Account", question: "How do I update my birth details?", answer: "Go to Birth Profile in your dashboard sidebar. Keeping this accurate matters — it's used by every personalized tool on the platform." },
  { id: "m-account-2", category: "Account", question: "How do I enable two-factor authentication?", answer: "Go to your account security settings to set up 2FA with an authenticator app for extra protection on your account." },
];

export const PRACTITIONER_FAQ: FaqEntry[] = [
  { id: "p-payout-1", category: "Payouts", question: "When do I get paid for completed sessions?", answer: "Payouts are processed on the studio's regular payout cycle. Check Earnings in your practitioner dashboard for your current balance and payout history." },
  { id: "p-payout-2", category: "Payouts", question: "How is my earning per session calculated?", answer: "You earn based on the service price for each completed, paid session, visible per booking under Bookings and summarized under Earnings." },
  { id: "p-schedule-1", category: "Schedule", question: "How do I set my availability?", answer: "Go to Schedule to set your weekly working hours and block out time off. Clients can only book slots within your published availability." },
  { id: "p-schedule-2", category: "Schedule", question: "Can I block out time for a vacation?", answer: "Yes — use the time-off feature on the Schedule page to mark specific dates unavailable; existing bookings in that window are unaffected." },
  { id: "p-booking-1", category: "Bookings", question: "Where do I see my upcoming sessions?", answer: "Bookings lists every session — past and upcoming — with the client's birth details and any notes they've shared." },
  { id: "p-booking-2", category: "Bookings", question: "Can I see a client's full details before the session?", answer: "Yes — expand any booking to see the client's birth date, time, place, and notes, plus the option to auto-generate their Kundli summary." },
  { id: "p-kundli-1", category: "Client Tools", question: "How do I generate a client's Kundli summary?", answer: "Open Bookings, expand the client's session, and click Generate Kundli Summary. It computes their real chart (not AI) from the birth details captured at booking — instant and free, no Gemini/AI cost involved." },
  { id: "p-kundli-2", category: "Client Tools", question: "Is the Kundli summary saved for next time?", answer: "Yes — once generated, it's cached on the booking, so you (and only you, for your own bookings) can revisit it anytime without regenerating." },
  { id: "p-review-1", category: "Reviews", question: "How do reviews work?", answer: "Clients can leave a review after a completed session. Reviews go through moderation before appearing on your public profile." },
  { id: "p-profile-1", category: "Profile", question: "How do I update my profile photo and bio?", answer: "Go to Profile to update your photo, title, bio, and specialties — this is what clients see on the marketplace." },
  { id: "p-notif-1", category: "Notifications", question: "How do I get notified about new bookings?", answer: "The notification bell in your dashboard alerts you to new bookings, cancellations, and messages in real time." },
];
