import "server-only";

import { db } from "@/lib/firestore";
import { query } from "@/lib/postgres";
import { isSupabaseCutoverActive } from "@/lib/supabase-config";
import { creditWalletBonus, type Wallet } from "@/lib/wallet";

/**
 * An administrator crediting a member's wallet by hand: a refund for a reading that failed, a
 * missed session, or goodwill. Members are told to "contact support for a refund" when a paid
 * reading cannot be produced, and until this existed support had no way to give one.
 */

export class AdminCreditError extends Error {}

export const ADMIN_CREDIT_MAX = 50000;

export type AdminCreditInput = { memberId: string; amount: number; reason: string; requestId: string };

/** Checks the input and returns it cleaned up, or throws AdminCreditError with a message the admin
 * can act on. `requestId` is generated by the form once per submission, so a double click or a
 * retried request credits once, not twice. */
export function parseAdminCredit(body: Record<string, unknown>): AdminCreditInput {
  const memberId = typeof body.memberId === "string" ? body.memberId.trim() : "";
  const reason = typeof body.reason === "string" ? body.reason.trim() : "";
  const requestId = typeof body.requestId === "string" ? body.requestId.trim() : "";
  const amount = typeof body.amount === "number" ? body.amount : Number.NaN;

  if (!memberId) throw new AdminCreditError("Choose the member to credit.");
  if (!Number.isInteger(amount) || amount < 1 || amount > ADMIN_CREDIT_MAX) {
    throw new AdminCreditError(`Enter a whole amount between 1 and ${ADMIN_CREDIT_MAX}.`);
  }
  if (reason.length < 3 || reason.length > 200) throw new AdminCreditError("Give a reason of 3 to 200 characters.");
  if (!/^[A-Za-z0-9-]{8,64}$/.test(requestId)) throw new AdminCreditError("Invalid request. Reload the page and try again.");
  return { memberId, amount, reason, requestId };
}

async function findMember(memberId: string): Promise<{ name: string; email: string } | null> {
  if (isSupabaseCutoverActive()) {
    const result = await query<{ name: string; email: string }>(`select name, email from public.members where id = $1`, [memberId]);
    return result.rows[0] ?? null;
  }
  const snap = await db.collection("members").doc(memberId).get();
  if (!snap.exists) return null;
  const data = snap.data() as { name?: string; email?: string };
  return { name: data.name ?? "", email: data.email ?? "" };
}

/** Credits the wallet once per requestId. Refuses an unknown member rather than opening a wallet
 * for an id that belongs to nobody. */
export async function creditWalletByAdmin(input: AdminCreditInput): Promise<{ wallet: Wallet; member: { name: string; email: string } }> {
  const member = await findMember(input.memberId);
  if (!member) throw new AdminCreditError("That member no longer exists.");
  const wallet = await creditWalletBonus({
    memberId: input.memberId,
    amount: input.amount,
    type: "admin_credit",
    referenceType: "admin_credit",
    referenceId: `admin-credit-${input.requestId}`,
  });
  return { wallet, member };
}
