"use client";

import { FormEvent, useMemo, useState } from "react";
import { Check, ChevronDown, Inbox, LockKeyhole, MailPlus, MessageSquareText, MoreHorizontal, Search, Send, Trash2, UserRound, X } from "lucide-react";

export type MessageItem={id:string;threadId:string;senderType:string;senderName:string;body:string;readByMember:boolean;readByAdmin:boolean;createdAt:Date|string};
export type MessageThreadItem={id:string;memberId:string;bookingId:string|null;subject:string;category:string;status:string;lastMessageAt:Date|string;createdAt:Date|string;updatedAt:Date|string;memberName:string;memberEmail:string;messages:MessageItem[]};
type MemberOption={id:string;name:string;email:string};

export function AdminMessages({initialThreads,members}:{initialThreads:MessageThreadItem[];members:MemberOption[]}){
  const [threads,setThreads]=useState(initialThreads);const [selectedId,setSelectedId]=useState(initialThreads[0]?.id??null);const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [reply,setReply]=useState("");const [sending,setSending]=useState(false);const [compose,setCompose]=useState(false);const [notice,setNotice]=useState("");const [draft,setDraft]=useState({memberId:String(members[0]?.id??""),subject:"",category:"general",message:""});
  const selected=threads.find(t=>t.id===selectedId)??null;
  const visible=useMemo(()=>threads.filter(t=>{const matches=`${t.subject} ${t.memberName} ${t.memberEmail}`.toLowerCase().includes(query.toLowerCase());const unread=t.messages.some(m=>m.senderType==="member"&&!m.readByAdmin);return matches&&(filter==="all"||(filter==="unread"?unread:t.status===filter));}),[threads,query,filter]);
  async function choose(thread:MessageThreadItem){setSelectedId(thread.id);if(thread.messages.some(m=>m.senderType==="member"&&!m.readByAdmin)){await fetch(`/api/messages/${thread.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({markRead:true})});setThreads(current=>current.map(t=>t.id===thread.id?{...t,messages:t.messages.map(m=>({...m,readByAdmin:true}))}:t));}}
  async function sendReply(event:FormEvent){event.preventDefault();if(!selected||!reply.trim())return;setSending(true);const response=await fetch(`/api/messages/${selected.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:reply})});const data=await response.json();if(response.ok){setThreads(current=>current.map(t=>t.id===selected.id?{...t,status:"open",lastMessageAt:data.createdAt,messages:[...t.messages,data]}:t));setReply("");setNotice("Reply sent.");}else setNotice(data.error||"Reply could not be sent.");setSending(false);}
  async function setStatus(status:string){if(!selected)return;const response=await fetch(`/api/messages/${selected.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(response.ok){setThreads(current=>current.map(t=>t.id===selected.id?{...t,status}:t));setNotice(status==="closed"?"Conversation closed.":"Conversation reopened.");}}
  async function remove(){if(!selected||!window.confirm("Delete this entire conversation?"))return;const response=await fetch(`/api/messages/${selected.id}`,{method:"DELETE"});if(response.ok){const remaining=threads.filter(t=>t.id!==selected.id);setThreads(remaining);setSelectedId(remaining[0]?.id??null);setNotice("Conversation deleted.");}}
  async function create(event:FormEvent){event.preventDefault();setSending(true);const response=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const data=await response.json();if(response.ok){setThreads(current=>[data,...current]);setSelectedId(data.id);setCompose(false);setDraft({memberId:String(members[0]?.id??""),subject:"",category:"general",message:""});setNotice("New conversation sent.");}else setNotice(data.error||"Message could not be sent.");setSending(false);}
  const unread=threads.reduce((sum,t)=>sum+t.messages.filter(m=>m.senderType==="member"&&!m.readByAdmin).length,0);
  return <>
    <div className="message-admin-heading"><div><p>Jyotish / Communication</p><h1>Messages</h1><span>Personal support and booking communication with your members.</span></div><button className="button button--small" onClick={()=>setCompose(true)}><MailPlus size={15}/> New message</button></div>
    <section className="messaging-workspace admin-message-workspace">
      <aside className="thread-pane"><div className="thread-pane__title"><span><Inbox size={17}/><strong>Inbox</strong></span><em>{unread} unread</em></div><div className="thread-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations…"/></div><div className="thread-filters">{["all","unread","open","closed"].map(item=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div><div className="thread-list">{visible.map(thread=>{const last=thread.messages.at(-1);const isUnread=thread.messages.some(m=>m.senderType==="member"&&!m.readByAdmin);return <button className={`${selectedId===thread.id?"selected":""} ${isUnread?"unread":""}`} onClick={()=>choose(thread)} key={thread.id}><span className="thread-avatar">{thread.memberName.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span><strong>{thread.memberName}</strong><small>{thread.subject}</small><i>{last?.body}</i></span><time>{new Date(thread.lastMessageAt).toLocaleDateString("en",{month:"short",day:"numeric"})}</time>{isUnread&&<b/>}</button>})}{!visible.length&&<div className="thread-empty"><MessageSquareText size={22}/><span>No conversations here</span></div>}</div></aside>
      <section className="conversation-pane">{selected?<><header><div className="conversation-member"><span>{selected.memberName.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><div><strong>{selected.memberName}</strong><small>{selected.memberEmail}</small></div></div><div className="conversation-subject"><small>{selected.category}{selected.bookingId?` · Booking #${selected.bookingId}`:""}</small><h2>{selected.subject}</h2></div><div className="conversation-tools"><span className={`conversation-state ${selected.status}`}>{selected.status}</span><button onClick={()=>setStatus(selected.status==="open"?"closed":"open")} title={selected.status==="open"?"Close thread":"Reopen thread"}><LockKeyhole size={15}/></button><button onClick={remove} title="Delete thread"><Trash2 size={15}/></button></div></header><div className="conversation-messages">{selected.messages.map(message=><article className={`message-bubble message-bubble--${message.senderType}`} key={message.id}><div><strong>{message.senderName}</strong><time>{new Date(message.createdAt).toLocaleString("en",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time></div><p>{message.body}</p></article>)}</div><form className="conversation-reply" onSubmit={sendReply}><textarea value={reply} onChange={e=>setReply(e.target.value)} disabled={selected.status==="closed"} placeholder={selected.status==="closed"?"Reopen this conversation to reply":"Write a thoughtful reply…"}/><div><small>Messages are visible only to this member.</small><button className="button button--small" disabled={sending||selected.status==="closed"}>{sending?"Sending…":<>Send reply <Send size={13}/></>}</button></div></form></>:<div className="conversation-empty"><MessageSquareText size={30}/><h2>Your studio inbox</h2><p>Select a conversation or begin a new message.</p></div>}</section>
    </section>
    {notice&&<div className="toast"><Check size={15}/>{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss"><X size={14}/></button></div>}
    {compose&&<div className="modal-backdrop" onMouseDown={()=>setCompose(false)}><section className="admin-modal compose-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><p>Direct communication</p><h2>New message</h2></div><button onClick={()=>setCompose(false)} aria-label="Close"><X size={20}/></button></div><form onSubmit={create}><label className="field"><span>Member</span><select value={draft.memberId} onChange={e=>setDraft({...draft,memberId:e.target.value})}>{members.map(m=><option value={m.id} key={m.id}>{m.name} · {m.email}</option>)}</select></label><label className="field"><span>Category</span><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option value="general">General</option><option value="booking">Booking</option><option value="billing">Billing</option><option value="support">Support</option></select></label><label className="field field--full"><span>Subject</span><input required value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})} placeholder="A clear subject"/></label><label className="field field--full"><span>Message</span><textarea required rows={6} value={draft.message} onChange={e=>setDraft({...draft,message:e.target.value})} placeholder="Write your message…"/></label><div className="modal-actions field--full"><button type="button" className="button button--ghost" onClick={()=>setCompose(false)}>Cancel</button><button className="button" disabled={sending}>{sending?"Sending…":"Send message"}</button></div></form></section></div>}
  </>;
}
