import { Bot } from "lucide-react";

/**
 * The label every AI persona carries wherever a customer can see it — marketplace card, profile,
 * homepage, chat. One component so the wording cannot drift between surfaces.
 *
 * 32 of the 34 seeded practitioners are AI personas with human names, and nothing used to say so:
 * they were listed as "Verified" with years of experience, and the chat model was told to speak
 * "like a real experienced astrologer". The site's own About page promises not to "dress up
 * generated text as a live human when it isn't".
 */
export const AI_PERSONA_LABEL = "AI astrologer";
export const AI_PERSONA_EXPLANATION = "Replies are generated by an AI model, not written by a person.";

/**
 * An AI persona cannot be senior or certified. Stored titles predate the disclosure and admins can
 * type anything, so the claim is removed where it is shown rather than trusted to the data.
 */
export function practitionerTitle(title: string, isAiPowered: boolean | undefined): string {
  if (!isAiPowered) return title;
  const stripped = title.replace(/\b(senior|certified|veteran|renowned)\s+/gi, "").trim();
  return stripped ? stripped.charAt(0).toUpperCase() + stripped.slice(1) : AI_PERSONA_LABEL;
}

export function AiPersonaBadge({ compact = false }: { compact?: boolean }) {
  return (
    <span className="ai-persona-badge" title={AI_PERSONA_EXPLANATION}>
      <Bot size={compact ? 12 : 14} aria-hidden="true" />
      {AI_PERSONA_LABEL}
    </span>
  );
}
