"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link } from "@/i18n/navigation";
import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, Clock3, LoaderCircle, LockKeyhole, Mail, MapPin, Orbit, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { trackEvent } from "@/lib/track-event";

export type BookingService = { id:string;title:string;category:string;description:string;price:number;duration:number;featured:boolean };
type BookingMember={name:string;email:string;phone:string|null;birthDate:string|null;birthTime:string|null;birthPlace:string|null};
type Practitioner={id:string;name:string;title:string;bio:string;specialties:string;featured:boolean};
type Slot={practitionerId:string;practitionerName:string;startsAt:string;label:string};
type BookingResult={reference:string;serviceTitle:string;servicePrice:number;scheduledAt:string;clientEmail:string;practitionerName:string|null};
function localDateAfter(days:number){const date=new Date();date.setDate(date.getDate()+days);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}

export function BookingFlow({services,initialServiceId,initialPractitionerId,member,cancellationHours=24,discountPercent=0}:{services:BookingService[];initialServiceId?:string;initialPractitionerId?:string;member?:BookingMember|null;cancellationHours?:number;discountPercent?:number}){
  const[step,setStep]=useState(1);const[serviceId,setServiceId]=useState(initialServiceId&&services.some(x=>x.id===initialServiceId)?initialServiceId:services[0]?.id);const[birthDate,setBirthDate]=useState(member?.birthDate??"");const[birthTime,setBirthTime]=useState(member?.birthTime??"");const[birthPlace,setBirthPlace]=useState(member?.birthPlace??"");const[clientName,setClientName]=useState(member?.name??"");const[clientEmail,setClientEmail]=useState(member?.email??"");const[clientPhone,setClientPhone]=useState(member?.phone??"");const[date,setDate]=useState(localDateAfter(1));const[practitioners,setPractitioners]=useState<Practitioner[]>([]);const[practitionerId,setPractitionerId]=useState<string|null>(null);const[slots,setSlots]=useState<Slot[]>([]);const[selectedSlot,setSelectedSlot]=useState("");const[timezone,setTimezone]=useState("");const[loadingSlots,setLoadingSlots]=useState(false);const[notes,setNotes]=useState("");const[error,setError]=useState("");const[submitting,setSubmitting]=useState(false);const[result,setResult]=useState<BookingResult|null>(null);
  const selected=useMemo(()=>services.find(x=>x.id===serviceId),[services,serviceId]);const selectedPractitioner=practitioners.find(x=>x.id===practitionerId);const practitionerSlots=slots.filter(x=>x.practitionerId===practitionerId);const discountedPrice=selected?Math.max(0,Math.round(selected.price*(100-discountPercent)/100)):0;
  useEffect(()=>{if(step!==3||!serviceId||!date)return;let active=true;Promise.resolve().then(()=>{if(active){setLoadingSlots(true);setSelectedSlot("");}});fetch(`/api/availability?date=${date}&serviceId=${serviceId}`).then(async response=>{const data=await response.json();if(!active)return;if(response.ok){setPractitioners(data.practitioners);setSlots(data.slots);setTimezone(data.timezone);const ids=new Set<string>(data.slots.map((slot:Slot)=>slot.practitionerId));setPractitionerId(current=>current&&ids.has(current)?current:(initialPractitionerId&&ids.has(initialPractitionerId)?initialPractitionerId:(data.slots[0]?.practitionerId??null)));setError(data.slots.length?"":"No open times on this date. Try another day.");}else setError(data.error||"Availability could not be loaded.");}).catch(()=>active&&setError("Availability could not be loaded.")).finally(()=>active&&setLoadingSlots(false));return()=>{active=false};},[step,serviceId,date,initialPractitionerId]);
  function continueFlow(){setError("");if(step===1&&!selected)return setError("Choose a reading to continue.");if(step===2&&(!birthDate||!birthTime||!birthPlace.trim()))return setError("Complete your birth date, exact time, and place.");setStep(current=>Math.min(3,current+1));}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected||!practitionerId||!selectedSlot)return setError("Choose an astrologer and available time.");if(!clientName.trim()||!/^\S+@\S+\.\S+$/.test(clientEmail))return setError("Enter your name and a valid email address.");setSubmitting(true);setError("");try{const response=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceId,practitionerId,bookingDate:date,clientName,clientEmail,clientPhone,birthDate,birthTime,birthPlace,scheduledAt:selectedSlot,notes})});const data=await response.json();if(!response.ok)throw new Error(data.error||"We could not reserve this time.");trackEvent("purchase",{value:data.servicePrice,currency:"INR",item_category:"booking"});setResult(data);}catch(caught){setError(caught instanceof Error?caught.message:"Something went wrong. Please try again.");setSelectedSlot("");}finally{setSubmitting(false);}}
  if(!member)return <div className="ask-signin" style={{margin:"40px auto"}}><UserRound size={26}/><h2>Sign in to book a consultation</h2><p>Create a free account or sign in to reserve your time with an astrologer. Every booking is then tracked from your dashboard.</p><div className="ask-signin__actions"><Link href="/account?mode=register" className="button">Create account</Link><Link href="/account" className="button button--ghost">Sign in</Link></div></div>;
  if(result){const appointment=new Date(result.scheduledAt);return <section className="booking-success"><div className="success-orbit"><CheckCircle2 size={35}/></div><p className="eyebrow"><span/>Your place is reserved</p><h1>The stars are<br/><em>in motion.</em></h1><p>A confirmation has been prepared for <strong>{result.clientEmail}</strong>. {result.practitionerName} will review your birth details before the session.</p><div className="booking-receipt"><div><small>Reading</small><strong>{result.serviceTitle}</strong></div><div><small>Astrologer</small><strong>{result.practitionerName}</strong></div><div><small>Date & time</small><strong>{appointment.toLocaleDateString("en",{weekday:"short",month:"long",day:"numeric",timeZone:timezone||undefined})} · {appointment.toLocaleTimeString("en",{hour:"numeric",minute:"2-digit",timeZone:timezone||undefined})}</strong></div><div><small>Reservation</small><strong>{result.reference}</strong></div><div><small>Amount</small><strong>₹{result.servicePrice}{discountPercent>0&&<i> · {discountPercent}% membership discount applied</i>}</strong></div></div><div className="booking-success__actions"><Link href="/dashboard" className="button">Open dashboard <ArrowRight size={16}/></Link><Link href="/" className="button button--ghost">Return home</Link></div></section>}
  return <div className="booking-layout"><section className="booking-panel"><div className="booking-progress">{[1,2,3].map(number=><div className={number<=step?"active":""} key={number}><span>{number<step?<Check size={12}/>:number}</span><small>{["Reading","Birth details","Schedule"][number-1]}</small></div>)}</div><form onSubmit={submit}>
    {step===1&&<div className="booking-step"><div className="booking-step__heading"><p>Step one</p><h1>Choose your<br/><em>reading.</em></h1><span>Select the guidance that feels most useful for this season.</span></div><div className="booking-services">{services.map(service=><button type="button" className={service.id===serviceId?"selected":""} onClick={()=>setServiceId(service.id)} key={service.id}><span className="booking-service-icon">{service.featured?<Sparkles size={18}/>:<Orbit size={18}/>}</span><span><small>{service.category} · {service.duration} min</small><strong>{service.title}</strong><i>{service.description}</i></span><b>₹{service.price}</b><span className="selection-dot"><Check size={11}/></span></button>)}</div></div>}
    {step===2&&<div className="booking-step"><div className="booking-step__heading"><p>Step two</p><h1>Map your<br/><em>first sky.</em></h1><span>Accuracy matters. Use the exact details shown on your birth record whenever possible.</span></div><div className="booking-fields"><label><span>Birth date</span><div><CalendarDays size={16}/><input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)}/></div></label><label><span>Exact birth time</span><div><Clock3 size={16}/><input type="time" value={birthTime} onChange={e=>setBirthTime(e.target.value)}/></div><small>Not sure? Enter your closest known time.</small></label><label className="wide"><span>Birth place</span><div><MapPin size={16}/><input value={birthPlace} onChange={e=>setBirthPlace(e.target.value)} placeholder="City, country"/></div></label></div><div className="privacy-note"><ShieldCheck size={18}/><p><strong>Your birth data stays private.</strong><span>It is used only to calculate your chart and prepare this reading.</span></p></div></div>}
    {step===3&&<div className="booking-step"><div className="booking-step__heading"><p>Final step</p><h1>Choose your<br/><em>guide & moment.</em></h1><span>Availability is shown in {timezone||"the studio timezone"} and protected from double booking.</span></div><div className="booking-fields"><label><span>Your name</span><div><UserRound size={16}/><input value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Full name"/></div></label><label><span>Email address {member&&<i>verified account</i>}</span><div><Mail size={16}/><input type="email" readOnly={Boolean(member)} value={clientEmail} onChange={e=>setClientEmail(e.target.value)}/></div></label><label><span>Preferred date</span><div><CalendarDays size={16}/><input type="date" min={localDateAfter(0)} value={date} onChange={e=>setDate(e.target.value)}/></div></label><label><span>Phone <i>optional</i></span><div><input value={clientPhone} onChange={e=>setClientPhone(e.target.value)} placeholder="+1 555 0100"/></div></label><fieldset className="wide practitioner-options"><legend>Choose your astrologer</legend>{loadingSlots?<div className="availability-loading"><LoaderCircle size={18}/>Finding open times…</div>:practitioners.map(person=>{const available=slots.some(slot=>slot.practitionerId===person.id);return <button type="button" disabled={!available} className={practitionerId===person.id?"selected":""} onClick={()=>{setPractitionerId(person.id);setSelectedSlot("")}} key={person.id}><span>{person.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><div><strong>{person.name}</strong><small>{person.title}</small><i>{person.specialties}</i></div>{available?<b>{slots.filter(slot=>slot.practitionerId===person.id).length} times</b>:<b>Full</b>}</button>})}</fieldset><fieldset className="wide time-slots"><legend>Available times {selectedPractitioner&&`with ${selectedPractitioner.name}`}</legend>{practitionerSlots.map(slot=><button type="button" className={selectedSlot===slot.startsAt?"selected":""} onClick={()=>setSelectedSlot(slot.startsAt)} key={slot.startsAt}>{slot.label}</button>)}{!loadingSlots&&!practitionerSlots.length&&<span className="no-slots">Choose another astrologer or date.</span>}</fieldset><label className="wide"><span>What would you like to explore? <i>optional</i></span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Share questions or themes for your astrologer."/></label></div></div>}
    {error&&<p className="booking-error" role="alert">{error}</p>}<div className="booking-actions">{step>1?<button type="button" className="back-link" onClick={()=>{setError("");setStep(step-1)}}><ArrowLeft size={15}/>Back</button>:<Link className="back-link" href="/"><ArrowLeft size={15}/>Home</Link>}{step<3?<button type="button" className="button" onClick={continueFlow}>Continue <ArrowRight size={16}/></button>:<button className="button" disabled={submitting||loadingSlots||!selectedSlot}>{submitting?"Reserving…":"Reserve consultation"}<ArrowRight size={16}/></button>}</div>
  </form></section><aside className="booking-summary"><div className="booking-summary__art"><span>✦</span><Orbit size={110} strokeWidth={.45}/></div><p>Your selection</p><h2>{selected?.title??"Choose a reading"}</h2><div><span><UserRound size={14}/>Astrologer</span><strong>{selectedPractitioner?.name??"Choose a guide"}</strong></div><div><span><Clock3 size={14}/>Duration</span><strong>{selected?.duration??0} minutes</strong></div><div className="booking-total"><span>Total</span><strong>{discountPercent>0&&selected?<><s>₹{selected.price}</s> ₹{discountedPrice}</>:`₹${selected?.price??0}`}</strong></div>{discountPercent>0&&<p className="summary-note"><Sparkles size={13}/>{discountPercent}% membership discount applied.</p>}<p className="summary-note"><LockKeyhole size={13}/>No payment is collected today. Changes are available up to {cancellationHours} hours before the call.</p></aside></div>;
}
