"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CircleDollarSign, CreditCard, FileText, LockKeyhole, ReceiptText, ShieldCheck, X } from "lucide-react";
import type { FinanceInvoice } from "@/components/admin-billing";

export function MemberBilling({invoices,onlinePaymentsAvailable,checkoutState}:{invoices:FinanceInvoice[];onlinePaymentsAvailable:boolean;checkoutState?:string}){const[loading,setLoading]=useState<number|null>(null);const[notice,setNotice]=useState(checkoutState==="success"?"Payment submitted. Your receipt will appear after secure confirmation.":checkoutState==="cancelled"?"Checkout was cancelled. Your invoice remains open.":"");const outstanding=invoices.filter(x=>x.status==="open").reduce((s,x)=>s+x.amount,0);const paid=invoices.filter(x=>x.status==="paid").reduce((s,x)=>s+x.amount,0);async function checkout(id:number){setLoading(id);const response=await fetch(`/api/member/invoices/${id}/checkout`,{method:"POST"});const data=await response.json();if(response.ok&&data.url)window.location.assign(data.url);else{setNotice(data.error||"Checkout could not be started.");setLoading(null);}}
  return <><div className="consultation-heading billing-heading"><div><p>Private financial history</p><h1>Billing & receipts</h1><span>Clear invoices and payment records for every consultation.</span></div><Link href="/book" className="button button--small">Book a reading <ArrowRight size={14}/></Link></div><section className="member-billing-summary"><article><span><ReceiptText size={19}/></span><div><small>Invoices</small><strong>{invoices.length}</strong></div></article><article><span><CreditCard size={19}/></span><div><small>Outstanding</small><strong>${outstanding}</strong></div></article><article><span><CircleDollarSign size={19}/></span><div><small>Paid to date</small><strong>${paid}</strong></div></article><article><span><ShieldCheck size={19}/></span><div><small>Checkout</small><strong>{onlinePaymentsAvailable?"Secure online":"Studio assisted"}</strong></div></article></section><div className="member-finance-note"><LockKeyhole size={17}/><span><strong>Your financial details stay private.</strong><small>Online payments are hosted by Stripe when enabled; card details never pass through Jyotish servers.</small></span></div><section className="member-invoice-card"><header><div><p>Consultation ledger</p><h2>Your invoices</h2></div><span>{invoices.length} total</span></header><div className="member-invoice-list">{invoices.map(invoice=><article key={invoice.id}><div className="member-invoice-icon"><FileText size={18}/></div><div className="member-invoice-name"><small>{invoice.number} · {invoice.bookingReference}</small><h3>{invoice.description}</h3><p>Issued {new Date(invoice.createdAt).toLocaleDateString("en",{month:"long",day:"numeric",year:"numeric"})}</p></div><div className="member-invoice-amount"><strong>{invoice.currency} {invoice.amount}</strong><span className={`invoice-status invoice-status--${invoice.status}`}>{invoice.status.replace("_"," ")}</span></div><div className="member-invoice-actions"><Link href={`/dashboard/billing/${invoice.id}`}>View receipt</Link>{invoice.status==="open"&&(onlinePaymentsAvailable?<button disabled={loading===invoice.id} onClick={()=>checkout(invoice.id)}>{loading===invoice.id?"Opening…":"Pay securely"}</button>:<span>Pay through studio</span>)}</div></article>)}{!invoices.length&&<div className="consultation-empty"><ReceiptText size={26}/><h3>No invoices yet</h3><p>Your consultation invoices and receipts will appear here.</p><Link href="/book" className="button button--small">Explore readings</Link></div>}</div></section>{notice&&<div className="toast"><Check size={15}/>{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}</>;
}
