"use client";

import { FormEvent, useMemo, useState } from "react";
import { Check, Inbox, MailPlus, MessageCircleMore, Search, Send, Sparkles, X } from "lucide-react";
import type { MessageThreadItem,MessageItem } from "@/components/admin-messages";

export function MemberInbox({initialThreads}:{initialThreads:MessageThreadItem[]}){
  const [threads,setThreads]=useState(initialThreads);const [selectedId,setSelectedId]=useState(initialThreads[0]?.id??null);const [query,setQuery]=useState("");const [reply,setReply]=useState("");const [compose,setCompose]=useState(false);const [sending,setSending]=useState(false);const [notice,setNotice]=useState("");const [draft,setDraft]=useState({subject:"",category:"support",message:""});
  const visible=useMemo(()=>threads.filter(t=>`${t.subject} ${t.category}`.toLowerCase().includes(query.toLowerCase())),[threads,query]);const selected=threads.find(t=>t.id===selectedId)??null;const unread=threads.reduce((sum,t)=>sum+t.messages.filter(m=>m.senderType!=="member"&&!m.readByMember).length,0);
  async function choose(thread:MessageThreadItem){setSelectedId(thread.id);if(thread.messages.some(m=>m.senderType!=="member"&&!m.readByMember)){await fetch(`/api/member/messages/${thread.id}`,{method:"PUT"});setThreads(current=>current.map(t=>t.id===thread.id?{...t,messages:t.messages.map(m=>({...m,readByMember:true}))}:t));}}
  async function replyToThread(event:FormEvent){event.preventDefault();if(!selected||!reply.trim())return;setSending(true);const response=await fetch(`/api/member/messages/${selected.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:reply})});const data=await response.json();if(response.ok){setThreads(current=>current.map(t=>t.id===selected.id?{...t,lastMessageAt:data.createdAt,messages:[...t.messages,data as MessageItem]}:t));setReply("");setNotice("Your reply was sent.");}else setNotice(data.error||"Reply could not be sent.");setSending(false);}
  async function create(event:FormEvent){event.preventDefault();setSending(true);const response=await fetch("/api/member/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const data=await response.json();if(response.ok){setThreads(current=>[data,...current]);setSelectedId(data.id);setCompose(false);setDraft({subject:"",category:"support",message:""});setNotice("Your message was sent to the studio.");}else setNotice(data.error||"Message could not be sent.");setSending(false);}
  return <>
    <div className="consultation-heading inbox-heading"><div><p>Private communication</p><h1>Studio inbox</h1><span>Booking updates and thoughtful support, kept together.</span></div><button className="button button--small" onClick={()=>setCompose(true)}><MailPlus size={15}/> Ask the studio</button></div>
    <section className="messaging-workspace member-message-workspace"><aside className="thread-pane"><div className="thread-pane__title"><span><Inbox size={17}/><strong>Conversations</strong></span>{unread>0&&<em>{unread} new</em>}</div><div className="thread-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your inbox…"/></div><div className="thread-list member-thread-list">{visible.map(thread=>{const last=thread.messages.at(-1);const isUnread=thread.messages.some(m=>m.senderType!=="member"&&!m.readByMember);return <button className={`${selectedId===thread.id?"selected":""} ${isUnread?"unread":""}`} onClick={()=>choose(thread)} key={thread.id}><span className={`thread-avatar thread-avatar--${thread.category}`}><Sparkles size={14}/></span><span><strong>{thread.subject}</strong><small>{thread.category} · {thread.status}</small><i>{last?.body}</i></span><time>{new Date(thread.lastMessageAt).toLocaleDateString("en",{month:"short",day:"numeric"})}</time>{isUnread&&<b/>}</button>})}{!visible.length&&<div className="thread-empty"><MessageCircleMore size={22}/><span>No conversations yet</span></div>}</div></aside><section className="conversation-pane">{selected?<><header className="member-conversation-header"><div className="conversation-subject"><small>{selected.category}{selected.bookingId?" · Consultation update":""}</small><h2>{selected.subject}</h2></div><span className={`conversation-state ${selected.status}`}>{selected.status}</span></header><div className="conversation-messages">{selected.messages.map(message=><article className={`message-bubble message-bubble--${message.senderType}`} key={message.id}><div><strong>{message.senderType==="member"?"You":message.senderName}</strong><time>{new Date(message.createdAt).toLocaleString("en",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time></div><p>{message.body}</p></article>)}</div><form className="conversation-reply" onSubmit={replyToThread}><textarea value={reply} onChange={e=>setReply(e.target.value)} disabled={selected.status==="closed"} placeholder={selected.status==="closed"?"This conversation has been closed":"Write a reply…"}/><div><small>The studio usually replies within one business day.</small><button className="button button--small" disabled={sending||selected.status==="closed"}>{sending?"Sending…":<>Send <Send size={13}/></>}</button></div></form></>:<div className="conversation-empty"><MessageCircleMore size={30}/><h2>Your private inbox</h2><p>Select a conversation or ask the studio a question.</p></div>}</section></section>
    {notice&&<div className="toast"><Check size={15}/>{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
    {compose&&<div className="modal-backdrop" onMouseDown={()=>setCompose(false)}><section className="admin-modal compose-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><p>Private member support</p><h2>Ask the studio</h2></div><button onClick={()=>setCompose(false)}><X size={20}/></button></div><form onSubmit={create}><label className="field"><span>Topic</span><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option value="support">Chart support</option><option value="booking">Booking</option><option value="billing">Billing</option><option value="general">General</option></select></label><label className="field"><span>Subject</span><input required value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})} placeholder="How can we help?"/></label><label className="field field--full"><span>Your message</span><textarea required rows={6} value={draft.message} onChange={e=>setDraft({...draft,message:e.target.value})} placeholder="Share the details you would like us to know…"/></label><div className="modal-actions field--full"><button type="button" className="button button--ghost" onClick={()=>setCompose(false)}>Cancel</button><button className="button" disabled={sending}>{sending?"Sending…":"Send to studio"}</button></div></form></section></div>}
  </>;
}
