import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight,CheckCircle2,ShieldCheck,Sparkles } from "lucide-react";
import { MarketplaceExplorer } from "@/components/marketplace-explorer";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { getCurrentMember } from "@/lib/member-auth";
import { getFavoritePractitionerIds,getMarketplacePractitioners } from "@/lib/marketplace";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Vedic Astrologers",description:"Meet verified Vedic astrologers for thoughtful private readings, transparent specialties, and real-time scheduling.",openGraph:{title:"Verified Vedic Astrologers · Jyotish",description:"Choose a thoughtful guide by specialty, language, experience, and availability.",url:"/astrologers"}};
export default async function AstrologersPage({searchParams}:{searchParams:Promise<{q?:string}>}){const[{q},people,member]=await Promise.all([searchParams,getMarketplacePractitioners(),getCurrentMember()]);const favorites=member?await getFavoritePractitionerIds(member.id):[];const cards=people.map(person=>({id:person.id,slug:person.slug,name:person.name,title:person.title,bio:person.bio,specialties:person.specialties,languages:person.languages,consultationModes:person.consultationModes,experienceYears:person.experienceYears,verified:person.verified,verificationLevel:person.verificationLevel,photoUrl:person.photoUrl,online:person.online,featured:person.featured,rating:person.rating,reviewCount:person.reviewCount,chatRatePerMinute:person.chatRatePerMinute,availableDays:new Set(person.rules.filter(rule=>rule.active).map(rule=>rule.weekday)).size}));return <main className="marketplace-page"><SiteHeader/><section className="marketplace-hero shell"><div><p className="eyebrow"><span/>The Jyotish guide collective</p><h1>Meet the person<br/><em>behind the reading.</em></h1><p>Choose a practitioner by method, language, lived experience, and the kind of conversation you need—not by a noisy popularity contest.</p><div><Link className="button" href="#experts">Find your guide <ArrowRight size={16}/></Link><Link className="button button--ghost" href="/book">Browse open times</Link></div></div><aside><div className="marketplace-hero-photo"><Image src="/images/astrologers-hero.jpg" alt="Hands unrolling an astrological birth chart scroll beside a compass, under a starry sky" fill sizes="(max-width: 720px) 100vw, 480px" style={{ objectFit: "cover" }} priority /></div><div className="marketplace-trust"><article><CheckCircle2 size={17}/><span><strong>Identity & method reviewed</strong><small>Every published guide passes studio review.</small></span></article><article><ShieldCheck size={17}/><span><strong>Private by design</strong><small>Your birth details stay within your care journey.</small></span></article><article><Sparkles size={17}/><span><strong>Real consultation reviews</strong><small>Only completed sessions can be reviewed.</small></span></article></div></aside></section><section className="marketplace-body shell" id="experts"><div className="marketplace-heading"><div><p>Choose with confidence</p><h2>Practitioners, not profiles<br/><em>optimized for clicks.</em></h2></div><span>Our ordering favors fit, verification, experience, and availability. New guides are not penalized for having fewer reviews.</span></div><MarketplaceExplorer people={cards} favoriteIds={favorites} memberSignedIn={Boolean(member)} initialQuery={q??""}/></section><SiteFooter/></main>;}
