import type { Metadata } from "next";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { getStudioSettings } from "@/lib/studio-settings";

// Same content for every visitor (admin settings, no auth check) — see about/page.tsx.
export const revalidate = 3600;
export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Jyotish collects, uses, and protects your account, birth, and payment information.",
  openGraph: { title: "Jyotish Privacy Policy", description: "How we collect, use, and protect your information.", url: "/privacy" },
};

export default async function PrivacyPage() {
  const settings = await getStudioSettings();
  return (
    <main className="marketing-page legal-page">
      <SiteHeader />
      <section className="legal-hero shell">
        <p className="eyebrow"><span /> Legal</p>
        <h1>Privacy Policy</h1>
        <p>Your birth details are among the most personal information you can share. Here is exactly what we collect, why, and how it&rsquo;s protected.</p>
        <span className="legal-updated">Last updated 30 July 2026</span>
      </section>

      <section className="shell legal-body">
        <h2>1. Information we collect</h2>
        <p>We collect information you give us directly, and a small amount generated by using the Service:</p>
        <ul>
          <li><strong>Account information</strong> — name, email, phone number, and a securely hashed password (or, if you sign in with Google, an identifier from Google — we never see your Google password).</li>
          <li><strong>Birth details</strong> — birth date, time, and place, used to compute your astrological chart, Panchang, matches, and readings. This is the most sensitive information you provide us.</li>
          <li><strong>Consultation content</strong> — chat messages, session notes, and reviews created while using the marketplace.</li>
          <li><strong>Payment information</strong> — handled by Razorpay; we store the resulting transaction ID and amount, never your full card, UPI, or bank number.</li>
          <li><strong>Usage information</strong> — pages visited, device/browser type, and IP address, used for security (rate limiting, fraud prevention) and, where analytics is enabled, aggregate product improvement.</li>
        </ul>

        <h2>2. How we use it</h2>
        <ul>
          <li>To calculate your astrological charts, matches, and readings.</li>
          <li>To connect you with a practitioner and process bookings and payments.</li>
          <li>To send you service messages — booking confirmations, payment receipts, and account security notices.</li>
          <li>To protect the Service against abuse, fraud, and unauthorized access.</li>
          <li>To improve the Service, where you have not opted out of analytics.</li>
        </ul>
        <p>We do not sell your personal information, and we do not use your birth details for anything beyond generating the readings and matches you request.</p>

        <h2>3. Who we share it with</h2>
        <p>Your birth details and consultation content are shared only with the practitioner you choose to book or chat with, so they can prepare and deliver your reading. We also share limited data with service providers who help us run Jyotish, each bound to use it only for that purpose:</p>
        <ul>
          <li><strong>Razorpay</strong> — payment processing.</li>
          <li><strong>Google (Gemini API)</strong> — generates AI reading text from the question and chart context you provide; Google does not use this data to train its own models when accessed via the API.</li>
          <li><strong>Resend</strong> — delivers transactional emails (receipts, confirmations).</li>
          <li><strong>Pusher / Ably</strong> — powers real-time chat delivery.</li>
          <li><strong>Firebase (Google)</strong> — if you choose to sign in with Google, authenticates that sign-in.</li>
        </ul>
        <p>We may also disclose information if required by law, or to protect the rights, safety, and property of Adi Jyotish Guru, our users, or the public.</p>

        <h2>4. Data retention</h2>
        <p>We retain your account and birth details for as long as your account is active, so your charts and history remain available to you. If you delete your account, we remove or anonymize your personal data within a reasonable period, except where we&rsquo;re required to retain transaction records for accounting or legal purposes.</p>

        <h2>5. Your rights</h2>
        <p>You can access and update most of your information directly from your account settings. You may also request a copy of your data, ask us to correct it, or ask us to delete your account and associated personal data, by writing to <a href={`mailto:${settings.supportEmail}`}>{settings.supportEmail}</a>. We will respond within a reasonable time.</p>

        <h2>6. Cookies</h2>
        <p>We use essential cookies to keep you signed in securely (httpOnly, same-site session cookies) — these aren&rsquo;t optional, as the Service can&rsquo;t function without them. Where analytics is enabled on the Service, it may set additional cookies to understand aggregate usage; this never includes your birth details or consultation content.</p>

        <h2>7. Security</h2>
        <p>Passwords are stored using one-way hashing, never in plain text. Session cookies are marked httpOnly and secure. Payment details never touch our servers directly — they go straight to Razorpay. We use rate limiting and progressive lockouts to slow down automated attacks on login and other sensitive endpoints.</p>

        <h2>8. Children</h2>
        <p>Jyotish is not directed at children under 18. We do not knowingly collect information from anyone under 18; if you believe a minor has created an account, contact us and we will remove it.</p>

        <h2>9. Changes to this policy</h2>
        <p>We may update this policy as the Service evolves. Material changes will be reflected by the &ldquo;Last updated&rdquo; date above.</p>

        <h2>10. Contact</h2>
        <p>Questions or requests about your data can be sent to <a href={`mailto:${settings.supportEmail}`}>{settings.supportEmail}</a>.</p>

        <div className="legal-note">This document is a general template appropriate for an early-stage consultation and e-commerce platform. It has not been reviewed by a lawyer — please have it checked against your specific data-protection obligations (including India&rsquo;s DPDP Act, and GDPR if you serve EU users) before relying on it commercially.</div>
      </section>
      <SiteFooter />
    </main>
  );
}
