import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft,CheckCircle2,Clock3,Download,FileText,ShieldCheck } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import { PrintReceiptButton } from "@/components/print-receipt-button";
import { getMemberBilling } from "@/lib/billing";
import { getCurrentMember } from "@/lib/member-auth";
import { getStudioSettings } from "@/lib/studio-settings";

export const dynamic="force-dynamic";
export default async function ReceiptPage({params}:{params:Promise<{id:string}>}){const member=await getCurrentMember();if(!member)return null;const[{id:raw},settings,rows]=await Promise.all([params,getStudioSettings(),getMemberBilling(member.id,member.email)]);const invoice=rows.find(row=>row.id===raw);if(!invoice)notFound();const payment=invoice.payments[0];return <main className="receipt-page"><div className="receipt-actions"><Link href="/dashboard/billing"><ArrowLeft size={14}/>Back to billing</Link><a className="button button--small print-receipt-button" href={`/api/member/invoices/${invoice.id}/pdf`} download><Download size={14}/>Download PDF</a><PrintReceiptButton/></div><article className="receipt-document"><header><BrandMark/><div><small>Invoice</small><strong>{invoice.number}</strong></div></header><section className="receipt-title"><div><p>{invoice.status==="paid"?<CheckCircle2 size={21}/>:<Clock3 size={21}/>} {invoice.status==="paid"?"Payment receipt":"Invoice statement"}</p><h1>{invoice.description}</h1></div><span className={`invoice-status invoice-status--${invoice.status}`}>{invoice.status.replace("_"," ")}</span></section><section className="receipt-parties"><div><small>From</small><strong>{settings.studioName}</strong><span>{settings.supportEmail}</span>{settings.gstin&&<span>GSTIN {settings.gstin}</span>}</div><div><small>Bill to</small><strong>{invoice.customerName}</strong><span>{invoice.customerEmail}</span></div></section><section className="receipt-line-items"><div><span>Description</span><span>Reference</span><span>Amount</span></div><article><span><FileText size={16}/><strong>{invoice.description}</strong></span><span>{invoice.bookingReference}</span><strong>{invoice.currency} {invoice.subtotal.toFixed(2)}</strong></article><footer><span>Subtotal</span><strong>{invoice.currency} {invoice.subtotal.toFixed(2)}</strong></footer><footer><span>GST ({invoice.taxRate}%)</span><strong>{invoice.currency} {invoice.taxAmount.toFixed(2)}</strong></footer><footer><span>Total</span><strong>{invoice.currency} {invoice.amount.toFixed(2)}</strong></footer></section><section className="receipt-meta"><div><small>Issued</small><strong>{invoice.createdAt.toLocaleDateString("en",{month:"long",day:"numeric",year:"numeric"})}</strong></div><div><small>Consultation</small><strong>{invoice.scheduledAt.toLocaleString("en",{dateStyle:"medium",timeStyle:"short"})}</strong></div><div><small>Astrologer</small><strong>{invoice.practitionerName??"Jyotish Studio"}</strong></div><div><small>Payment method</small><strong>{payment?.provider??"Pending"}</strong></div><div><small>Paid</small><strong>{invoice.paidAt?invoice.paidAt.toLocaleDateString("en",{month:"long",day:"numeric",year:"numeric"}):"Not yet paid"}</strong></div></section><footer><ShieldCheck size={15}/><span>This invoice was generated securely by {settings.studioName}. Questions? Contact {settings.supportEmail}.</span></footer></article></main>;}
